name: ubuntu

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup prerequisites
        run: |
          sudo apt-get install xsltproc

      - name: XSD documentation generataion
        run: |
          make all
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add doc
          git commit -m "XSD docs generated"
          git push

#      - uses: actions/upload-artifact@v2
#        with:
#          name: published-ubuntu
#          path: doc
          
